- name: Install the Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Systemd nginx
  ansible.builtin.systemd_service:
    state: started
    name: nginx
    enabled: yes

- name: Clear html contents of nginx
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Download frontend files
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /tmp/frontend.zip

- name: Copy Config file to destination
  ansible.builtin.copy:
    src: /files/roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

