- name: Disable mysql
  ansible.builtin.shell: dnf module disable mysql -y

- name: Copy mysql repo
  ansible.builtin.template:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: Make sure mysql running
  ansible.builtin.systemd:
    name: mysqld
    daemon-reload: yes
    enabled: yes
    state: restarted

- name: change mysql root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
