- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop

- name: Remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create an Application directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive {{component}} files
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app
    remote_src: yes