- name: Install MAven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Import app-requirements task
  ansible.builtin.include_tasks: app-req.yml

- name: Clean packages maven
  ansible.builtin.shell: mvn clean package
  args:
    chdir: /app

- name: Import systemd task
  ansible.builtin.include_tasks: systemd.yml

- name: Import Mysql schema task
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load
