- name: Disable Nodejs and enable Nodejs:18
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Disable Nodejs and enable Nodejs:18
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Import app-pre-req task
  ansible.builtin.include_tasks: app-req.yml


- name: Install NPM dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Import systemd task
  ansible.builtin.include_tasks: systemd.yml


- name: Import schema task
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load

