- name: Copy {{component}} Systemd file to destination
  ansible.builtin.template:
    src: "{{component}}.service"
    dest: /etc/systemd/system/{{component}}.service

- name: Make sure a {{component}} service unit is running
  ansible.builtin.systemd:
    name: "{{component}}"
    daemon-reload: yes
    enabled: yes
    state: restarted